package com.customclearancecost.entity;

public enum CountryOfOrigin {
    NOT_DEFINED("не визначена"),
    AUSTRALIA("АВСТРАЛІЯ"),
    AUSTRIA("АВСТРІЯ"),
    AZERBAIJAN("АЗЕРБАЙДЖАН"),
    LAND_ISLANDS("АЛАНДСЬКІ ОСТРОВИ"),
    ALBANIA("АЛБАНІЯ"),
    ALGERIA("АЛЖИР"),
    AMERICAN_SAMOA("АМЕРИКАНСЬКЕ САМОА"),
    ANGELIA("АНҐІЛЬЯ"),
    ANGOLA("АНҐОЛА"),
    ANDORRA("АНДОРРА"),
    ANTARCTIDE("АНТАРКТИДА"),
    ANTIHUA_AND_BARBUDA("АНТИҐУА І БАРБУДА"),
    ARGENTINA("АРГЕНТИНА"),
    ARUBA("АРУБА"),
    AFGHANISTAN("АФГАНІСТАН"),
    BAGAMI("БАГАМИ"),
    BANGLADESH("БАНҐЛАДЕШ"),
    BARBADOS("БАРБАДОС"),
    BAKERYN("БАХРЕЙН"),
    BELIZE("БЕЛІЗ"),
    BELGIUM("БЕЛЬҐІЯ"),
    BENIN("БЕНІН"),
    BERMUDAS("БЕРМУДИ"),
    BELARUS("БІЛОРУСЬ"),
    BULGARIA("БОЛГАРІЯ"),
    BOLIVIA("БОЛІВІЯ"),
    BOSNIA_AND_HERZEGOVINA("БОСНІЯ І ГЕРЦЕҐОВИНА"),
    BOTSWANA("БОТСВАНА"),
    BRAZIL("БРАЗИЛІЯ"),
    BRITISH_TERRITORY_IN_THE_INDIAN_OCEAN("БРИТАНСЬКА ТЕРИТОРІЯ В ІНДІЙСЬКОМУ ОКЕАНІ"),
    BRUNE_DARUSSALAM("БРУНЕЙ-ДАРУССАЛАМ"),
    BURKINA_FASO("БУРКІНА-ФАСО"),
    BURUNDI("БУРУНДІ"),
    BUTANE("БУТАН"),
    VANUATU("ВАНУАТУ"),
    VENEZUELA("ВЕНЕСУЕЛА"),
    VIETNAM("В'ЄТНАМ"),
    VIRGIN_ISLANDS_BRITISH("ВІРҐІНСЬКІ ОСТРОВИ (БРИТАНСЬКІ)"),
    VIRGIN_ISLANDS_USA("ВІРҐІНСЬКІ ОСТРОВИ (США)"),
    ARMENIA("ВІРМЕНІЯ"),
    GABON("ҐАБОН"),
    HAITI("ГАЇТІ"),
    GUYANA("ҐАЙАНА"),
    GAMBIA("ҐАМБІЯ"),
    GANA("ГАНА"),
    GVADELUPA("ҐВАДЕЛУПА"),
    GWATEMALA("ҐВАТЕМАЛА"),
    GUINEA("ҐВІНЕЯ"),
    GUINEA_BISSAU("ҐВІНЕЯ-БІСАУ"),
    GERNS("ГЕРНСІ"),
    GIBRALTAR("ҐІБРАЛТАР"),
    HONDURAS("ГОНДУРАС"),
    HUNKONG("ГОНКОНҐ"),
    GRENADES("ҐРЕНАДА"),
    GREENLAND("ҐРЕНЛАНДІЯ"),
    GREECE("ГРЕЦІЯ"),
    GEORGIA("ГРУЗІЯ"),
    GUAM("ҐУАМ"),
    DANIEL("ДАНІЯ"),
    DEMOCRATIC_REPUBLIC_OF_CONGO("ДЕМОКРАТИЧНА РЕСПУБЛІКА КОНҐО"),
    JERSEY("ДЖЕРСІ"),
    JIBUTI("ДЖІБУТІ"),
    DOMINICA("ДОМІНІКА"),
    DOMINICAN_REPUBLIC("ДОМІНІКАНСЬКА РЕСПУБЛІКА"),
    ECUADOR("ЕКВАДОР"),
    EQUATORIAL_GUINEA("ЕКВАТОРІАЛЬНА ҐВІНЕЯ"),
    ERITREY("ЕРІТРЕЯ"),
    ESTONIA("ЕСТОНІЯ"),
    ETHIOPIA("ЕФІОПІЯ"),
    EGYPT("ЄГИПЕТ"),
    YEMEN("ЄМЕН"),
    ZAMBIA("ЗАМБІЯ"),
    WESTERN_SAHARA("ЗАХІДНА САХАРА"),
    ZIMBABWE("ЗІМБАБВЕ"),
    ISRAEL("ІЗРАЇЛЬ"),
    INDIA("ІНДІЯ"),
    INDONESIA("ІНДОНЕЗІЯ"),
    IRAQ("ІРАК"),
    IRAN_ISLAMIC_REPUBLIC("ІРАН, ІСЛАМСЬКА РЕСПУБЛІКА"),
    IRELAND("ІРЛАНДІЯ"),
    ICELAND("ІСЛАНДІЯ"),
    SPAIN("ІСПАНІЯ"),
    ITALY("ІТАЛІЯ"),
    JORDAN("ЙОРДАНІЯ"),
    CABO_VERDE("КАБО-ВЕРДЕ"),
    KAZAKHSTAN("КАЗАХСТАН"),
    CAMBODIA("КАМБОДЖА"),
    CAMEROON("КАМЕРУН"),
    CANADA("КАНАДА"),
    QATAR("КАТАР"),
    KENYA("КЕНІЯ"),
    KYRGYZSTAN("КИРГИЗСТАН"),
    CHINA("КИТАЙ"),
    CYPRUS("КІПР"),
    KIRIBATI("КІРІБАТІ"),
    COCOBIC_CILING_ISLANDS("КОКОСОВІ (КІЛІНҐ) ОСТРОВИ"),
    COLOMBIA("КОЛУМБІЯ"),
    COMORIA("КОМОРИ"),
    CONGO("КОНҐО"),
    KOREAN_PEOPLES_DEMOCRATIC_REPUBLIC("КОРЕЙСЬКА НАРОДНО-ДЕМОКРАТИЧНА РЕСПУБЛІКА"),
    KOREA("КОРЕЯ"),
    COSTA_RICA("КОСТА-РИКА"),
    KOT_DIVUAR("КОТ-Д'ІВУАР"),
    CUBA("КУБА"),
    KUWAIT("КУВЕЙТ"),
    LAO_PEOPLES_DEMOCRATIC_REPUBLIC("ЛАОСЬКА НАРОДНО-ДЕМОКРАТИЧНА РЕСПУБЛІКА"),
    LATVIA("ЛАТВІЯ"),
    LESOTHO("ЛЕСОТО"),
    LITHUANIA("ЛИТВА"),
    LIBERIA("ЛІБЕРІЯ"),
    LEBANON("ЛІВАН"),
    LIVAY_ARAB_JAMAHIRIYA("ЛІВІЙСЬКА АРАБСЬКА ДЖАМАХІРІЯ"),
    LICHTENSHTEIN("ЛІХТЕНШТЕЙН"),
    LUXEMBOURG("ЛЮКСЕМБУРҐ"),
    MAVRIKIY("МАВРИКІЙ"),
    MAURITANIA("МАВРИТАНІЯ"),
    MADAGASCAR("МАДАҐАСКАР"),
    MAITOTA("МАЙОТТА"),
    MACAO("МАКАО"),
    MACEDONIA("МАКЕДОНІЯ"),
    MALAVI("МАЛАВІ"),
    MALAYSIA("МАЛАЙЗІЯ"),
    MALI("МАЛІ"),
    US_MINOR_OUTLYING_ISLANDS("МАЛІ ВІДДАЛЕНІ ОСТРОВИ СПОЛУЧЕНИХ ШТАТІВ"),
    MALDIVI("МАЛЬДІВИ"),
    MALTA("МАЛЬТА"),
    MOROCCO("МАРОККО"),
    MARTINICA("МАРТІНІКА"),
    MARSHALL_ISLANDS("МАРШАЛЛОВІ ОСТРОВИ"),
    MEXICO("МЕКСИКА"),
    MICRONESIA("МІКРОНЕЗІЯ"),
    MOZAMBIQUE("МОЗАМБІК"),
    MOLDOVA("МОЛДОВА"),
    MONACO("МОНАКО"),
    MONGOLIA("МОНГОЛІЯ"),
    MONTHSERRATE("МОНТСЕРРАТ"),
    MYANMA("М'ЯНМА"),
    NAMIBIA("НАМІБІЯ"),
    NAURU("НАУРУ"),
    NEPAL("НЕПАЛ"),
    NIGER("НІҐЕР"),
    NIGERIA("НІҐЕРІЯ"),
    NETHERLANDS("НІДЕРЛАНДИ"),
    THE_NETHERLANDS_ANTIC_ISLANDS("НІДЕРЛАНДСЬКІ АНТИЛЬСЬКІ ОСТРОВИ"),
    NICARAGUA("НІКАРАҐУА"),
    GERMANY("НІМЕЧЧИНА"),
    NONE("НІУЕ"),
    NEW_ZEALAND("НОВА ЗЕЛАНДІЯ"),
    NEW_CALEDONIA("НОВА КАЛЕДОНІЯ"),
    NORWAY("НОРВЕҐІЯ"),
    THE_UNITED_REPUBLIC_OF_TANZANIA("ОБ'ЄДНАНА РЕСПУБЛІКА ТАНЗАНІЯ"),
    UNITED_ARAB_EMIRATES("ОБ'ЄДНАНІ АРАБСЬКІ ЕМІРАТИ"),
    OMAN("ОМАН"),
    ISLANDS_WAS_YOU("ОСТРІВ БУВЕ"),
    ISLAND_OF_ME("ОСТРІВ МЕН"),
    NORFOLK_ISLANDS("ОСТРІВ НОРФОЛК"),
    ISLANDS_OF_RISK("ОСТРІВ РІЗДВА"),
    ISLAND_OF_THE_HOLY_JELEN("ОСТРІВ СВЯТОЇ ЄЛЕН"),
    ISLANDS_HARD_AND_ISLANDS_MACDONALD("ОСТРІВ ХЕРД І ОСТРОВИ МАКДОНАЛЬД"),
    ISLANDS_CAYMAN("ОСТРОВИ КАЙМАН"),
    KUKA_ISLANDS("ОСТРОВИ КУКА"),
    SWALBARD_ISLANDS_AND_JAN_MAYN("ОСТРОВИ СВАЛЬБАРД ТА ЯН-МАЄН"),
    PAKISTAN("ПАКИСТАН"),
    PALAU("ПАЛАУ"),
    PALESTINIAN_TERRITORY("ПАЛЕСТИНСЬКА ТЕРИТОРІЯ"),
    PANAMA("ПАНАМА"),
    PAPACY("ПАПСЬКИЙ ПРЕСТОЛ"),
    PAPUA_NEW_GVINIA("ПАПУА-НОВА ҐВІНЕЯ"),
    PARAGUAY("ПАРАҐВАЙ"),
    PERU("ПЕРУ"),
    SOUTH_AFRICA("ПІВДЕННА АФРИКА"),
    SOUTH_GEORGIA_AND_SOUTH_SANDWICH_ISLANDS("ПІВДЕННА ДЖОРДЖІЯ ТА ПІВДЕННІ САНДВІЧЕВІ ОСТРОВИ"),
    NORTH_MARIAN_ISLANDS("ПІВНІЧНІ МАРІАНСЬКІ ОСТРОВИ"),
    PITCHERN("ПІТКЕРН"),
    POLAND("ПОЛЬЩА"),
    PORTUGAL("ПОРТУҐАЛІЯ"),
    PURETO_RICO("ПУЕРТО-РИКО"),
    REUNION("РЕЮНЬЙОН"),
    RWANDA("РУАНДА"),
    ROMANIA("РУМУНІЯ"),
    SALVADOR("САЛЬВАДОР"),
    SAMOA("САМОА"),
    SAN_MARINO("САН-МАРИНО"),
    SAN_TOME_AND_PRINSIP("САН-ТОМЕ І ПРІНСІП"),
    SAUDI_ARABIA("САУДІВСЬКА АРАВІЯ"),
    SWAZILAND("СВАЗІЛЕНД"),
    SEISHES("СЕЙШЕЛИ"),
    SENEGAL("СЕНЕҐАЛ"),
    SEN_PERE_AND_MICELO("СЕН-П'ЄР І МІКЕЛО"),
    SEVEN_VINCENT_AND_GREENADINES("СЕНТ-ВІНСЕНТ І ҐРЕНАДІНИ"),
    SEAT_KITSE_AND_NEVIS("СЕНТ-КІТС І НЕВІС"),
    SENT_LUCIA("СЕНТ-ЛЮСІЯ"),
    SERBIA("СЕРБІЯ"),
    SINGAPORE("СІНҐАПУР"),
    SYRIA_ARAB_REPUBLIC("СИРІЙСЬКА АРАБСЬКА РЕСПУБЛІКА"),
    SLOVAKIA("СЛОВАЧЧИНА"),
    SLOVENIA("СЛОВЕНІЯ"),
    SOLOMON_ISLANDS("СОЛОМОНОВІ ОСТРОВИ"),
    SOMALIA("СОМАЛІ"),
    THE_UNITED_KINGDOM("СПОЛУЧЕНЕ КОРОЛІВСТВО"),
    UNITED_STATES("СПОЛУЧЕНІ ШТАТИ АМЕРИКИ"),
    SUDAN("СУДАН"),
    SURINAM("СУРІНАМ"),
    SIERRA_LEONE("СЬЄРРА-ЛЕОНЕ"),
    TAJIKISTAN("ТАДЖИКИСТАН"),
    THAILAND("ТАЇЛАНД"),
    TAIWAN_CHINA_PROVINCE("ТАЙВАНЬ, ПРОВІНЦІЯ КИТАЮ"),
    TERKS_AND_CAYKOS("ТЕРКС І КАЙКОС"),
    TIMOR_LESHTI("ТІМОР-ЛЕШТІ"),
    TOGO("ТОҐО"),
    TOKELAU("ТОКЕЛАУ"),
    TONGA("ТОНҐА"),
    TRINIDAD_AND_TOBACCO("ТРИНІДАД І ТОБАҐО"),
    TUVALU("ТУВАЛУ"),
    TUNISIA("ТУНІС"),
    TURKEY("ТУРЕЧЧИНА"),
    TURKMENISTAN("ТУРКМЕНІСТАН"),
    UGANDA("УҐАНДА"),
    HUNGARY("УГОРЩИНА"),
    UZBEKISTAN("УЗБЕКИСТАН"),
    UKRAINE("УКРАЇНА"),
    WALLIS_AND_FUTUNA("УОЛЛІС І ФУТУНА"),
    URUGUAY("УРУҐВАЙ"),
    FARES_ISLANDS("ФАРЕРСЬКІ ОСТРОВИ"),
    FIJI("ФІДЖІ"),
    PHILIPPINES("ФІЛІППІНИ"),
    FINLAND("ФІНЛЯНДІЯ"),
    FOLKLAND_ISLANDS_MALVINSKIY("ФОЛКЛЕНДСЬКІ ОСТРОВИ (МАЛЬВІНСЬКІ)"),
    FRANCE("ФРАНЦІЯ"),
    FRENCH_GVIANA("ФРАНЦУЗЬКА ҐВІАНА"),
    FRENCH_POLYNESIA("ФРАНЦУЗЬКА ПОЛІНЕЗІЯ"),
    FRENCH_SOUTHERN_TERRITORIES("ФРАНЦУЗЬКІ ПІВДЕННІ ТЕРИТОРІЇ"),
    CROATIA("ХОРВАТІЯ"),
    CENTRAL_AFRICAN_REPUBLIC("ЦЕНТРАЛЬНОАФРИКАНСЬКА РЕСПУБЛІКА"),
    CHAD("ЧАД"),
    CZECH_REPUBLIC("ЧЕСЬКА РЕСПУБЛІКА"),
    CHILE("ЧІЛІ"),
    MONTENEGRO("ЧОРНОГОРІЯ"),
    SWITZERLAND("ШВЕЙЦАРІЯ"),
    SWEDEN("ШВЕЦІЯ"),
    SRI_LANKA("ШРІ-ЛАНКА"),
    JAMAICA("ЯМАЙКА"),
    JAPAN("ЯПОНІЯ");

    CountryOfOrigin(String description) {
        this.description = description;
    }

    private String description;

    public String getDescription() {
        return description;
    }
}